development:
  adapter: postgresql
  encoding: utf8
  database: metricapp_development
  pool: 5
  username: nathan
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: metricapp_test
  pool: 5
  username: nathan
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: metricapp_production
  pool: 5
  username: nathan
  password:
